site_name: 'Documentació de les Tasques'
docs_dir: 'md_docs'
site_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'pink'
    background: 'white'
    surface: 'grey'
    error: 'red'

nav:
  - Inici: index.md
  - Articles EDD:
    - Articles MD:
      - Article 1 MD: EDD/md/TASCA1.md
      - Article 2 MD: EDD/md/TASCA2.md
      - Article 3 MD: EDD/md/TASCA3.md
      - Article 4 MD: EDD/md/TASCA4.md
    - Articles RSC-Subversion:
      - Article 1: EDD/RSC-Subversion/ACTIVITAT1.md
      - Article 2: EDD/RSC-Subversion/ACTIVITAT2.md
      - Article 3: EDD/RSC-Subversion/ACTIVITAT3.md
    - Articles Ant i Maven:
      - Article 1: EDD/Ant-Maven/ACTIVITAT1.mvn
  - Articles LMI:
    - Articles MD:
      - Article 1 MD: LMI/md/TASCA1.md
      - Article 2 MD: LMI/md/TASCA2.md
    - Articles HTML:
      - ARTICLE 1 HTML: LMI/html/ACTIVITAT1.html
      - ARTICLE 2 HTML: LMI/html/ACTIVITAT2.html
      - ARTICLE 3 HTML: LMI/html/ACTIVITAT3.html
      - ARTICLE 4 HTML: LMI/html/ACTIVITAT4.html
      - ARTICLE 5 HTML: LMI/html/ACTIVITAT5.html
      - ARTICLE 6 HTML: LMI/html/ACTIVITAT6.html
      - ARTICLE 7 HTML: LMI/html/ACTIVITAT7.html
      - ARTICLE 8 HTML: LMI/html/ACTIVITAT8.html
      - ARTICLE 9 HTML: LMI/html/ACTIVITAT9.html
      - ARTICLE 10 HTML: LMI/html/ACTIVITAT10.html
      - ARTICLE 11 HTML: LMI/html/ACTIVITAT11.html
      - ARTICLE 12 HTML: LMI/html/ACTIVITAT12.html
    - Articles JS:
      - ARTICLE 1 JS: LMI/js/ACTIVITAT1.js